// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLbzL51X8mZTZtqC9izxFUWTL5ghJYr8',
    appId: '1:838322152386:web:190a7b5210ad1bdc92ec5b',
    messagingSenderId: '838322152386',
    projectId: 'offline-first-pph-prediction',
    authDomain: 'offline-first-pph-prediction.firebaseapp.com',
    storageBucket: 'offline-first-pph-prediction.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA71W1vtuXHjhfcVcbEnOvKuOVNGcKucOQ',
    appId: '1:838322152386:android:b853ef7176ac76bb92ec5b',
    messagingSenderId: '838322152386',
    projectId: 'offline-first-pph-prediction',
    storageBucket: 'offline-first-pph-prediction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4_cPcIUAXGJlJL2rOp728RgqpLRly3s',
    appId: '1:838322152386:ios:5289bd37b54b7c8592ec5b',
    messagingSenderId: '838322152386',
    projectId: 'offline-first-pph-prediction',
    storageBucket: 'offline-first-pph-prediction.firebasestorage.app',
    androidClientId: '838322152386-rdh3c6e6idn5q4vo1jk770bsp3ft7asv.apps.googleusercontent.com',
    iosClientId: '838322152386-4r5lqlm6b9kd2m5tgpapdgt0ih0del2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE4_cPcIUAXGJlJL2rOp728RgqpLRly3s',
    appId: '1:838322152386:ios:5289bd37b54b7c8592ec5b',
    messagingSenderId: '838322152386',
    projectId: 'offline-first-pph-prediction',
    storageBucket: 'offline-first-pph-prediction.firebasestorage.app',
    androidClientId: '838322152386-rdh3c6e6idn5q4vo1jk770bsp3ft7asv.apps.googleusercontent.com',
    iosClientId: '838322152386-4r5lqlm6b9kd2m5tgpapdgt0ih0del2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuLbzL51X8mZTZtqC9izxFUWTL5ghJYr8',
    appId: '1:838322152386:web:b554b98ca5d4e27b92ec5b',
    messagingSenderId: '838322152386',
    projectId: 'offline-first-pph-prediction',
    authDomain: 'offline-first-pph-prediction.firebaseapp.com',
    storageBucket: 'offline-first-pph-prediction.firebasestorage.app',
  );
}
